# Generated by Django 4.2 on 2024-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0002_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(help_text='Physical address of the vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(default=0, help_text='Average time taken to acknowledge purchase orders'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_details',
            field=models.TextField(help_text='Contact information of the vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(default=0, help_text='Percentage of purchase orders fulfilled successfully'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Name of the vendor', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0, help_text='Percentage of on-time deliveries'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(default=0, help_text='Average rating of quality based on purchase orders'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(help_text='A unique identifier for the vendor', max_length=50, unique=True),
        ),
    ]
